name: DCO check
on: [pull_request]

jobs:
  dco_check_job:
    runs-on: ubuntu-latest
    steps:
    - name: DCO Check
      uses: jbryce/dco@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
